### ISSUE TITLE
Add CI support

### ISSUE THREAD

**Issue by brunoborges** [oracle/bosh-oracle-cpi#18]
For [Wercker](https://app.wercker.com/Oracle/) or [Travis CI](https://travis-ci.org/oracle/)

**Comment by dmutreja** [comment]
We have support for [Concourse](http://concourse.ci/index.html), the CI system of choice for all things BOSH and CloudFoundry.  Is there a particular use case that you have in mind that requires the CPI releases to be built on Wercker or Travis?

**Comment by brunoborges** [comment]
If this CPI is being already built under Concourse, can we have a build badge in the README file? If still not being built, then definitely something to add as it helps validate contributions (PRs) automatically.

Regarding Wercker/Travis vs Concourse, if the norm is Concourse for all things BOSH, that's OK. But having a build under Wercker would be nice, since we try to keep all projects on /oracle built under app.wercker.com/Oracle

**Comment by dmutreja** [comment]
@bitsarvi can you please investigate? Thanks.

**Comment by dmutreja** [comment]
This issue was moved to oracle/bosh-oracle-cpi-release#34
